# Generated by Django 4.0.5 on 2022-08-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter',
            new_name='twitter_url',
        ),
    ]
